# Generated by Django 5.1.3 on 2024-12-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('loSal', models.IntegerField(null=True)),
                ('hiSal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailID', models.IntegerField(unique=True)),
                ('Description', models.CharField(max_length=50, unique=True)),
                ('gradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grade')),
            ],
        ),
    ]
